# Generated by Django 5.2.15 on 2026-07-07 04:14

import django.db.models.deletion
import ourlives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Maximum number of tokens available across all invitation codes')),
            ],
            options={
                'verbose_name': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=ourlives.models.generate_invitation_code, help_text='Auto-generated unique code. May be overridden.', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_use', models.PositiveIntegerField(help_text='Number of tokens this code consumes from the pool')),
                ('current_use', models.PositiveIntegerField(default=0, help_text='Incremented by external service. Read-only in admin.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitation_codes', to='ourlives.project')),
            ],
            options={
                'verbose_name': 'Invitation Code',
                'verbose_name_plural': 'Invitation Codes',
                'constraints': [models.CheckConstraint(condition=models.Q(('current_use__lte', models.F('max_use'))), name='current_use_lte_max_use')],
            },
        ),
    ]
