# Generated by Django 5.2.15 on 2026-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(max_length=50)),
                ('token_count', models.PositiveIntegerField()),
                ('amount_cents', models.PositiveIntegerField(help_text='Amount in smallest currency units (cents for USD) from Stripe event payload')),
                ('handled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Event',
                'verbose_name_plural': 'Stripe Events',
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount in USD. Set to 0 for no minimum.', max_digits=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='price_per_token',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per token in USD. Set to 0 to disable purchasing.', max_digits=10),
        ),
    ]
