# Generated by Django 5.2.15 on 2026-07-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0002_stripeevent_appsettings_min_purchase_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text="Stripe Price ID (e.g., 'price_xxxxx'). Auto-populated by sync_stripe_price command.", max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text="Stripe Product ID (e.g., 'prod_xxxxx'). Auto-populated by sync_stripe_price command.", max_length=255),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='presentment_amount',
            field=models.PositiveIntegerField(blank=True, help_text="Amount in customer's currency smallest unit (e.g., cents for EUR) from presentment_details", null=True),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='presentment_currency',
            field=models.CharField(blank=True, help_text="ISO 4217 currency code (e.g., 'eur', 'gbp') that the customer saw at checkout", max_length=3),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='amount_cents',
            field=models.PositiveIntegerField(help_text='Settlement amount in smallest currency units (cents for USD) from Stripe event payload'),
        ),
    ]
