# Generated by Django 5.2.15 on 2026-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0006_alter_invitationcode_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for external service integration.', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='storage_base_url',
            field=models.URLField(blank=True, help_text='Base URL for external file storage.'),
        ),
    ]
