# Generated by Django 5.2.15 on 2026-07-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0007_appsettings_api_key_appsettings_storage_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='api_key',
        ),
    ]
