# Generated by Django 5.2.15 on 2026-09-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0010_contact_currency_organizationaddress_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.AddField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='currencies', to='ourlives.country'),
        ),
    ]
