# Generated by Django 5.2.17 on 2026-09-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0012_invitationcode_code_type_invitationcode_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
