# Generated by Django 5.2.17 on 2026-09-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0013_order_commission_paid_order_commission_paid_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rep_commission_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
