# Generated by Django 5.2.17 on 2026-09-25 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0014_order_rep_commission_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='form_webhook_token',
            field=models.CharField(blank=True, help_text='Shared secret validated against body.token on POST /webhooks/ourlens/.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Invitation codes created via webhook submissions for this order'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_addresses', to='ourlives.country'),
        ),
        migrations.CreateModel(
            name='FormWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Raw n8n request body as received by the webhook')),
                ('token', models.CharField(help_text='Shared secret verbatim (admin-only)', max_length=255)),
                ('event', models.CharField(blank=True, max_length=50)),
                ('execution_mode', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('created', 'Created'), ('updated', 'Updated'), ('error', 'Error')], default='rejected', max_length=20)),
                ('handled_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_webhook_events', to='ourlives.order')),
            ],
            options={
                'verbose_name': 'Form Webhook Event',
                'verbose_name_plural': 'Form Webhook Events',
                'ordering': ['-handled_at'],
            },
        ),
    ]
