# Generated by Django 5.2.15 on 2026-09-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourlives', '0015_appsettings_form_webhook_token_order_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_code_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_orders', to='ourlives.codetype'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_codes_bundle',
            field=models.CharField(blank=True, default='', help_text="Verbatim bundle label from the form (e.g. 'Up to 5 Additional Codes')", max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_codes_wanted',
            field=models.BooleanField(default=False, help_text='Form toggle: whether additional codes were requested'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Legacy webhook counter (frozen, no longer written); live code count comes from linked invitation codes'),
        ),
        migrations.CreateModel(
            name='OrderRequestedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Form slot number (code-N → N); gaps kept, e.g. missing 15')),
                ('value', models.CharField(max_length=50)),
                ('code_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_codes', to='ourlives.codetype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_codes', to='ourlives.order')),
            ],
            options={
                'verbose_name': 'Requested Code',
                'verbose_name_plural': 'Requested Codes',
                'ordering': ['order', 'sequence'],
            },
        ),
    ]
