# Generated by Django 5.2.15 on 2026-06-27 22:59

import core.models
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=core.models.avatar_upload_to, validators=[core.validators.validate_image_size])),
                ('primary_color', models.CharField(default='#C92FFF', max_length=7, validators=[core.validators.validate_hex_color, core.validators.validate_contrast_against_white])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
