# Generated by Django 5.2.15 on 2026-07-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_membership_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
