# Generated by Django 5.2.15 on 2026-07-03 22:47

from django.db import migrations
from django.utils.text import slugify


def set_slugs_and_default(apps, schema_editor):
    Brand = apps.get_model("core", "Brand")
    used_slugs = set()
    for brand in Brand.objects.all():
        slug = slugify(brand.name)
        if not slug:
            slug = f"brand-{brand.pk}"
        while slug in used_slugs:
            slug = f"{slug}-{brand.pk}"
        brand.slug = slug
        brand.save(update_fields=["slug"])
        used_slugs.add(slug)

    # Set is_default on the row matching DEFAULT_NAME
    Brand.objects.filter(name="Default Brand").update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_is_default_brand_slug'),
    ]

    operations = [
        migrations.RunPython(set_slugs_and_default, migrations.RunPython.noop),
    ]
